In [2]:
import data_engine as de
import pandas as pd
from feature_engine.discretisation import EqualWidthDiscretiser
from feature_engine.imputation import MeanMedianImputer,CategoricalImputer

In [12]:
data_save_path = './data/'
root_path = r'C:\\Users\\8prab\\Documents\\NSE_Equity_Futures_iEOD\\'
pattern = '*BANKNIFTY.txt'
data_name = 'banknifty'
#base_df= de.create_dataset(root_path,pattern,data_save_path,data_name)
base_df = pd.read_csv(r'C:\Users\8prab\Google Drive\Work\trading\data\banknifty\banknifty.csv')

In [13]:
base_df.shape

(1170729, 4)

In [16]:
import datetime as dt

from tqdm import tqdm

import pandas as pd
import pandas_ta as ta
CustomStrategy = ta.Strategy(
    name="Momo and Volatility",
    description="SMA 50,200, BBANDS, RSI, MACD and Volume SMA 20",
    ta=[
        {"kind": "sma", "length": 50},
        {"kind": "sma", "length": 200},
        {"kind": "bbands", "length": 20},
        {"kind": "rsi"},
        {"kind": "macd", "fast": 8, "slow": 21},
        {"kind": "sma", "close": "volume", "length": 20, "prefix": "VOLUME"},
    ]
)
# To run your "Custom Strategy"
base_df.ta.strategy()

0it [00:00, ?it/s]

In [15]:
base_df.shape

(1170729, 15)

In [11]:
base_df.index = pd.DatetimeIndex(base_df.index)
base_df.between_time('15:29','09:10')

,open,high,low,close,SMA_50,SMA_200,BBL_20_2.0,BBM_20_2.0,BBU_20_2.0,BBB_20_2.0,BBP_20_2.0,RSI_14,MACD_8_21_9,MACDh_8_21_9,MACDs_8_21_9
2018-04-02 09:08:00,24235.70,24235.70,24235.70,24235.70,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2018-04-02 15:29:00,24328.60,24334.10,24324.90,24332.30,24311.418,24267.57700,24314.183260,24339.5200,24364.856740,0.208194,0.357519,51.965035,1.651372,-5.283713,6.935086
2018-04-02 15:30:00,24331.60,24344.90,24323.80,24334.90,24313.282,24268.18250,24315.257269,24339.9550,24364.652731,0.202940,0.397663,53.359297,1.657583,-4.222002,5.879585
2018-04-02 15:31:00,24343.30,24343.30,24343.30,24343.30,24314.970,24268.81750,24317.136856,24340.8750,24364.613144,0.195048,0.551078,57.637477,2.731519,-2.518453,5.249972
2018-04-02 15:32:00,24346.30,24346.30,24328.50,24328.50,24316.012,24269.41600,24317.328706,24340.9350,24364.541294,0.193964,0.236617,49.093080,1.492250,-3.006177,4.498428
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2011-12-29 15:29:00,8003.60,8003.60,7987.55,7988.20,8053.646,8078.59400,7997.360930,8018.9675,8040.574070,0.538887,-0.211994,27.673314,-12.865251,-1.199125,-11.666126
2011-12-29 15:30:00,7990.95,7994.55,7986.75,7992.30,8051.653,8078.02125,7993.371723,8016.9575,8040.543277,0.588397,-0.022720,30.884677,-13.911497,-1.796296,-12.115200
2011-12-30 09:08:00,8073.20,8073.20,8073.20,8073.20,8051.225,8077.86875,7985.409209,8019.1175,8052.825791,0.840698,1.302214,64.437639,-3.746994,6.694565,-10.441559
2011-12-30 15:29:00,7959.45,7959.45,7953.30,7954.70,7958.582,8034.64500,7953.264243,7966.3225,7979.380757,0.327837,0.054975,42.866636,-2.837780,-2.342582,-0.495199
2011-12-30 15:30:00,7955.30,7956.90,7952.55,7954.75,7958.591,8034.00625,7951.687788,7965.6175,7979.547212,0.349746,0.109917,42.913977,-3.323059,-2.262289,-1.060771

In [ ]:
%%time
from sklearn.pipeline import Pipeline
shft_col_pat = ['close','open','high','low','momentum','volatile','transform','pattern','overlap']
shft_col_pat = ['close','open']

pipe = Pipeline([
     ('nd', de.NormalizeDataset(columns = ['close','open','high','low'],impute_values=True,impute_type = 'mean_median_imputer',convert_to_floats = True)),
     ('nd3', de.NormalizeDataset(column_pattern = ['close','open','high','low','momentum','volatile','transform','pattern','overlap'],drop_na_rows=False,fillna=True,fillna_method='ffill')),
   # ('pdrhw', de.PriceDayRangeHourWise(first_col = 'high',second_col='low',hour_range = [('09:00', '10:30'),('10:30', '11:30')],range_type=['price_range','price_deviation_max_first_col'])),
    #('pv', de.PricePerIncrement(freq='1min',shift=3,shift_column=[],shift_column_pattern=shft_col_pat,#verbose=False)),
    #('pltbc', de.PriceLastTickBreachCountv1(column_pattern=shft_col_pat,columns=[],last_ticks='10min',breach_type = ['morethan','max'])),
    #('pltbc2', de.PriceLastTickBreachCount(column_pattern=shft_col_pat,columns=[],create_new_col = True,last_ticks='10min',breach_type = ['morethan','max'])),
   # ('ppi', de.PricePerIncrement(freq='D',shift=5,shift_column=[],shift_column_pattern=['close','open','high','low','momentum','volatile','transform','pattern','overlap'],verbose=False)),
    ('pdrhw', de.PriceDayRangeHourWise(first_col = 'high',second_col='low',hour_range = [('09:00', '10:30'),('10:30', '11:30')],range_type=['price_range','price_deviation_max_first_col'])),
    ])
base_df2 = pipe.fit(base_df).transform(base_df)

In [ ]:
%%time
from sklearn.pipeline import Pipeline
shft_col_pat = ['close','open','high','low','momentum','volatile','transform','pattern','overlap']
shft_col_pat = ['close','open']

pipe = Pipeline([
     ('ctiuta', de.CreateTechnicalIndicatorUsingTA(open='open',high='high',low='low',close='close',volume='volume',fillna=False,colprefix='ta',volume_ta=False,volatility_ta=True,trend_ta=True,momentum_ta=True,others_ta=True)),
     ('nd3', de.NormalizeDataset(column_pattern = ['close','open','high','low','momentum','volatile','transform','pattern','overlap'],drop_na_rows=False,fillna=True,fillna_method='ffill')),
   # ('pdrhw', de.PriceDayRangeHourWise(first_col = 'high',second_col='low',hour_range = [('09:00', '10:30'),('10:30', '11:30')],range_type=['price_range','price_deviation_max_first_col'])),
    #('pv', de.PricePerIncrement(freq='1min',shift=3,shift_column=[],shift_column_pattern=shft_col_pat,#verbose=False)),
    #('pltbc', de.PriceLastTickBreachCountv1(column_pattern=shft_col_pat,columns=[],last_ticks='10min',breach_type = ['morethan','max'])),
    #('pltbc2', de.PriceLastTickBreachCount(column_pattern=shft_col_pat,columns=[],create_new_col = True,last_ticks='10min',breach_type = ['morethan','max'])),
   # ('ppi', de.PricePerIncrement(freq='D',shift=5,shift_column=[],shift_column_pattern=['close','open','high','low','momentum','volatile','transform','pattern','overlap'],verbose=False)),
    ('pdrhw', de.PriceDayRangeHourWise(first_col = 'high',second_col='low',hour_range = [('09:00', '10:30'),('10:30', '11:30')],range_type=['price_range','price_deviation_max_first_col'])),
    ])
base_df2 = pipe.fit(base_df2).transform(base_df2)

In [4]:

#from alphaVantageAPI.alphavantage import AlphaVantage  # pip install alphaVantage-api

#from watchlist import Watchlist # Is this failing? If so, copy it locally. See above.

name = All
description = All the indicators with their default settings. Pandas TA default.
created = Saturday April 9, 2022, NYSE: 9:58:06, Local: 13:58:06 India Standard Time, Day 99/365 (27.00%)
ta = None