In [1]:
import data_engine as de
import pandas as pd
from feature_engine.discretisation import EqualWidthDiscretiser
from feature_engine.imputation import MeanMedianImputer,CategoricalImputer

In [2]:
data_save_path = './data/'
root_path = r'C:\\Users\\8prab\\Documents\\NSE_Equity_Futures_iEOD\\'
pattern = '*BANKNIFTY.txt'
data_name = 'banknifty'
#base_df= de.create_dataset(root_path,pattern,data_save_path,data_name)
base_df = pd.read_csv(r'C:\Users\8prab\Google Drive\Work\trading\data\banknifty\banknifty.csv')

In [3]:
base_df.shape

(1170729, 4)

In [4]:
import datetime as dt

from tqdm import tqdm

import pandas as pd
import pandas_ta as ta
CustomStrategy = ta.Strategy(
    name="Momo and Volatility",
    description="SMA 50,200, BBANDS, RSI, MACD and Volume SMA 20",
    ta=[
        {"kind": "sma", "length": 50},
        {"kind": "sma", "length": 200},
        {"kind": "bbands", "length": 20},
        {"kind": "bbands", "length": 15},
        {"kind": "rsi", "length": 14},
        {"kind": "rsi", "length": 20},
        {"kind": "rsi", "length": 100},
        {"kind": "macd", "fast": 8, "slow": 21},
        {"kind": "macd", "fast": 15,"slow": 30},
        {"kind": "sma", "close": "volume", "length": 20, "prefix": "VOLUME"}
    ]
)
# To run your "Custom Strategy"
base_df.ta.strategy(CustomStrategy)

In [5]:
base_df

,open,high,low,close,SMA_50,SMA_200,BBL_20_2.0,BBM_20_2.0,BBU_20_2.0,BBB_20_2.0,...,BBP_15_2.0,RSI_14,RSI_20,RSI_100,MACD_8_21_9,MACDh_8_21_9,MACDs_8_21_9,MACD_15_30_9,MACDh_15_30_9,MACDs_15_30_9
20180402 09:08,24235.70,24235.70,24235.70,24235.70,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20180402 09:16,24268.00,24300.60,24243.70,24253.10,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20180402 09:17,24257.40,24286.10,24219.30,24221.40,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20180402 09:18,24222.60,24224.40,24204.00,24220.70,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20180402 09:19,24218.70,24247.10,24218.70,24229.40,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20111230 15:26,7955.80,7956.25,7954.30,7956.25,7958.872,8036.58000,7956.602683,7967.8625,7979.122317,0.282631,...,0.043712,43.377766,45.766682,44.678219,-1.912469,-3.234891,1.322422,0.471526,-1.544829,2.016354
20111230 15:27,7955.80,7959.90,7955.80,7959.80,7958.789,8035.94975,7955.756613,7967.5400,7979.323387,0.295785,...,0.214542,46.432151,47.620848,45.029602,-2.148030,-2.776361,0.628331,0.134347,-1.505606,1.639953
20111230 15:28,7960.90,7963.45,7960.90,7961.40,7958.670,8035.31300,7955.093015,7967.0850,7979.076985,0.301038,...,0.303423,47.798913,48.456877,45.188097,-2.061092,-2.151539,0.090447,-0.045960,-1.348730,1.302770
20111230 15:29,7959.45,7959.45,7953.30,7954.70,7958.582,8034.64500,7953.264243,7966.3225,7979.380757,0.327837,...,0.091503,42.866636,45.271787,44.643637,-2.837780,-2.342582,-0.495199,-0.598420,-1.520953,0.922532
20111230 15:30,7955.30,7956.90,7952.55,7954.75,7958.591,8034.00625,7951.687788,7965.6175,7979.547212,0.349746,...,0.152522,42.913977,45.300031,44.648664,-3.323059,-2.262289,-1.060771,-1.042786,-1.572255,0.529469

In [6]:
all_cols = [col for col in base_df.columns.tolist()]

In [7]:
all_cols

['open',
 'high',
 'low',
 'close',
 'SMA_50',
 'SMA_200',
 'BBL_20_2.0',
 'BBM_20_2.0',
 'BBU_20_2.0',
 'BBB_20_2.0',
 'BBP_20_2.0',
 'BBL_15_2.0',
 'BBM_15_2.0',
 'BBU_15_2.0',
 'BBB_15_2.0',
 'BBP_15_2.0',
 'RSI_14',
 'RSI_20',
 'RSI_100',
 'MACD_8_21_9',
 'MACDh_8_21_9',
 'MACDs_8_21_9',
 'MACD_15_30_9',
 'MACDh_15_30_9',
 'MACDs_15_30_9']

In [8]:
%%time
from sklearn.pipeline import Pipeline
shft_col_pat = ['close','open','high','low','momentum','volatile','transform','pattern','overlap']
shft_col_pat = ['close','open']
base_cols = ['close','open','high','low']

pipe = Pipeline([
     ('nd', de.NormalizeDataset(columns = all_cols,impute_values=True,impute_type = 'mean_median_imputer',convert_to_floats = True)),
     ('nd3', de.NormalizeDataset(columns = all_cols,drop_na_rows=False,fillna=True,fillna_method='ffill')),
     ('labelgenerator_1', de.LabelCreator(freq='1min',shift=-15,shift_column='close')),
     ('labelgenerator_2', de.LabelCreator(freq='1min',shift=-30,shift_column='close')),
     ('pdrhw', de.PriceDayRangeHourWise(first_col = 'RSI_100',second_col='RSI_20',hour_range = [('09:00', '10:30'),('10:30', '11:30')],range_type=['price_range','price_deviation_max_first_col'])),
     ('pdrhw2', de.PriceDayRangeHourWise(first_col = 'BBM_20_2.0',second_col='MACDs_8_21_9',hour_range = [('09:00', '10:30'),('10:30', '11:30')],range_type=['price_range','price_deviation_max_first_col'])),
     ('pdrhw3', de.PriceDayRangeHourWise(first_col = 'SMA_200',second_col='SMA_50',hour_range = [('09:00', '10:30'),('10:30', '11:30')],range_type=['price_range','price_deviation_max_first_col'])),
     ('pdrhw4', de.PriceDayRangeHourWise(first_col = 'BBM_15_2.0',second_col='BBM_20_2.0',hour_range = [('09:00', '10:30'),('10:30', '11:30')],range_type=['price_range','price_deviation_max_first_col'])),

     ('pv', de.PricePerIncrement(freq='1min',shift=3,shift_column=all_cols,shift_column_pattern=[],verbose=True)),
     #('pltbc2', de.PriceLastTickBreachCount(column_pattern=[],columns=all_cols,last_ticks='10min',breach_type = ['morethan','max'])),
     ('ppi', de.PricePerIncrement(freq='D',shift=5,shift_column=all_cols,shift_column_pattern=[],verbose=True)),
     ('pdrhw5', de.PriceDayRangeHourWise(first_col = 'high',second_col='low',hour_range = [('09:00', '10:30'),('10:30', '11:30')],range_type=['price_range','price_deviation_max_first_col'])),
     #('ctiuta', de.CreateTechnicalIndicatorUsingTA(open='open',high='high',low='low',close='close',volume='volume',fillna=False,colprefix='ta',volume_ta=False,volatility_ta=True,trend_ta=True,momentum_ta=True,others_ta=True,verbose=True)),
     #('a1', de.PositiveNegativeTrends(columns=base_cols,window=200,min_periods=None,verbose=True)),
     #('a2', de.BinningTransform(columns=base_cols,get_current_row_bin=False,n_bins=5,verbose=True)),
     #('a3', de.PercentileTransform(columns=base_cols,window=200,min_periods=20,verbose=True)),
     #('a4', de.WeightedExponentialAverage(columns=base_cols,com=None, span=44, halflife=None, alpha=None, min_periods=0, adjust=True, ignore_na=False, axis=0, times=None, method='single',verbose=True)),
     #('a6', de.LogTransform(columns=base_cols,verbose=True)),
     #('a7', de.Zscoring(columns=base_cols,verbose=True))
    ])
base_df2 = pipe.fit(base_df).transform(base_df)

2022-04-17 22:55:01,973 - ****************************************************************************************************
2022-04-17 22:55:13,889 - Shape of dataframe after NormalizeDataset is (1105219, 25) : convert_to_floats.convert_to_floats.convert_to_floats.convert_to_floats.convert_to_floats.convert_to_floats.convert_to_floats.convert_to_floats.convert_to_floats.convert_to_floats.convert_to_floats.convert_to_floats.convert_to_floats.convert_to_floats.convert_to_floats.convert_to_floats.convert_to_floats.convert_to_floats.convert_to_floats.convert_to_floats.convert_to_floats.convert_to_floats.convert_to_floats.convert_to_floats.convert_to_floats.mean_median_imputer
2022-04-17 22:55:14,235 - ****************************************************************************************************
2022-04-17 22:55:20,565 - Shape of dataframe after NormalizeDataset is (1105219, 25) : fillna
2022-04-17 22:55:23,544 - Shape of dataframe after transform is (1105219, 26)
2022-04-17 22:55:26,336 - Shape of dataframe after transform is (1105219, 27)
2022-04-17 22:55:26,389 - ****************************************************************************************************
2022-04-17 22:55:26,390 - PriceDayRangeHourWise : RSI_100 : RSI_20 : 09:00 : 10:30 : price_range
2022-04-17 22:55:26,566 - PriceDayRangeHourWise : RSI_100 : RSI_20 : 09:00 : 10:30 : price_deviation_max_first_col
2022-04-17 22:55:27,011 - PriceDayRangeHourWise : RSI_100 : RSI_20 : 10:30 : 11:30 : price_range
2022-04-17 22:55:27,149 - PriceDayRangeHourWise : RSI_100 : RSI_20 : 10:30 : 11:30 : price_deviation_max_first_col
2022-04-17 22:55:27,885 - Shape of dataframe after PriceDayRangeHourWise is (1108035, 29)
2022-04-17 22:55:27,926 - ****************************************************************************************************
2022-04-17 22:55:27,928 - PriceDayRangeHourWise : BBM_20_2.0 : MACDs_8_21_9 : 09:00 : 10:30 : price_range
2022-04-17 22:55:28,081 - PriceDayRangeHourWise : BBM_20_2.0 : MACDs_8_21_9 : 09:00 : 10:30 : price_deviation_max_first_col
2022-04-17 22:55:28,866 - PriceDayRangeHourWise : BBM_20_2.0 : MACDs_8_21_9 : 10:30 : 11:30 : price_range
2022-04-17 22:55:29,024 - PriceDayRangeHourWise : BBM_20_2.0 : MACDs_8_21_9 : 10:30 : 11:30 : price_deviation_max_first_col
2022-04-17 22:55:29,882 - Shape of dataframe after PriceDayRangeHourWise is (1108035, 31)
2022-04-17 22:55:29,950 - ****************************************************************************************************
2022-04-17 22:55:29,951 - PriceDayRangeHourWise : SMA_200 : SMA_50 : 09:00 : 10:30 : price_range
2022-04-17 22:55:30,099 - PriceDayRangeHourWise : SMA_200 : SMA_50 : 09:00 : 10:30 : price_deviation_max_first_col
2022-04-17 22:55:30,911 - PriceDayRangeHourWise : SMA_200 : SMA_50 : 10:30 : 11:30 : price_range
2022-04-17 22:55:31,042 - PriceDayRangeHourWise : SMA_200 : SMA_50 : 10:30 : 11:30 : price_deviation_max_first_col
2022-04-17 22:55:31,983 - Shape of dataframe after PriceDayRangeHourWise is (1108035, 33)
2022-04-17 22:55:32,064 - ****************************************************************************************************
2022-04-17 22:55:32,066 - PriceDayRangeHourWise : BBM_15_2.0 : BBM_20_2.0 : 09:00 : 10:30 : price_range
2022-04-17 22:55:32,209 - PriceDayRangeHourWise : BBM_15_2.0 : BBM_20_2.0 : 09:00 : 10:30 : price_deviation_max_first_col
2022-04-17 22:55:33,051 - PriceDayRangeHourWise : BBM_15_2.0 : BBM_20_2.0 : 10:30 : 11:30 : price_range
2022-04-17 22:55:33,206 - PriceDayRangeHourWise : BBM_15_2.0 : BBM_20_2.0 : 10:30 : 11:30 : price_deviation_max_first_col
2022-04-17 22:55:34,307 - Shape of dataframe after PriceDayRangeHourWise is (1108035, 35)
2022-04-17 22:55:34,471 - ****************************************************************************************************
2022-04-17 22:55:36,821 - Shape of dataframe after PricePerVelocity is (1108035, 60)
2022-04-17 22:55:36,891 - ****************************************************************************************************
2022-04-17 22:55:39,130 - Shape of dataframe after PricePerVelocity is (1108035, 85)
2022-04-17 22:55:39,295 - ****************************************************************************************************
2022-04-17 22:55:46,107 - Shape of dataframe after NormalizeDataset is (1105219, 25) : convert_to_floats.convert_to_floats.convert_to_floats.convert_to_floats.convert_to_floats.convert_to_floats.convert_to_floats.convert_to_floats.convert_to_floats.convert_to_floats.convert_to_floats.convert_to_floats.convert_to_floats.convert_to_floats.convert_to_floats.convert_to_floats.convert_to_floats.convert_to_floats.convert_to_floats.convert_to_floats.convert_to_floats.convert_to_floats.convert_to_floats.convert_to_floats.convert_to_floats.mean_median_imputer
2022-04-17 22:55:46,112 - ****************************************************************************************************
2022-04-17 22:55:47,280 - Shape of dataframe after NormalizeDataset is (1105219, 25) : fillna
2022-04-17 22:55:50,903 - Shape of dataframe after transform is (1105219, 26)
2022-04-17 22:55:54,191 - Shape of dataframe after transform is (1105219, 27)
2022-04-17 22:55:54,224 - ****************************************************************************************************
2022-04-17 22:55:54,227 - PriceDayRangeHourWise : RSI_100 : RSI_20 : 09:00 : 10:30 : price_range
2022-04-17 22:55:54,359 - PriceDayRangeHourWise : RSI_100 : RSI_20 : 09:00 : 10:30 : price_deviation_max_first_col
2022-04-17 22:55:54,693 - PriceDayRangeHourWise : RSI_100 : RSI_20 : 10:30 : 11:30 : price_range
2022-04-17 22:55:54,919 - PriceDayRangeHourWise : RSI_100 : RSI_20 : 10:30 : 11:30 : price_deviation_max_first_col
2022-04-17 22:55:56,151 - Shape of dataframe after PriceDayRangeHourWise is (1108035, 29)
2022-04-17 22:55:56,204 - ****************************************************************************************************
2022-04-17 22:55:56,205 - PriceDayRangeHourWise : BBM_20_2.0 : MACDs_8_21_9 : 09:00 : 10:30 : price_range
2022-04-17 22:55:56,384 - PriceDayRangeHourWise : BBM_20_2.0 : MACDs_8_21_9 : 09:00 : 10:30 : price_deviation_max_first_col
2022-04-17 22:55:57,449 - PriceDayRangeHourWise : BBM_20_2.0 : MACDs_8_21_9 : 10:30 : 11:30 : price_range
2022-04-17 22:55:57,589 - PriceDayRangeHourWise : BBM_20_2.0 : MACDs_8_21_9 : 10:30 : 11:30 : price_deviation_max_first_col
2022-04-17 22:55:58,346 - Shape of dataframe after PriceDayRangeHourWise is (1108035, 31)
2022-04-17 22:55:58,415 - ****************************************************************************************************
2022-04-17 22:55:58,416 - PriceDayRangeHourWise : SMA_200 : SMA_50 : 09:00 : 10:30 : price_range
2022-04-17 22:55:58,523 - PriceDayRangeHourWise : SMA_200 : SMA_50 : 09:00 : 10:30 : price_deviation_max_first_col
2022-04-17 22:55:59,389 - PriceDayRangeHourWise : SMA_200 : SMA_50 : 10:30 : 11:30 : price_range
2022-04-17 22:55:59,579 - PriceDayRangeHourWise : SMA_200 : SMA_50 : 10:30 : 11:30 : price_deviation_max_first_col
2022-04-17 22:56:00,959 - Shape of dataframe after PriceDayRangeHourWise is (1108035, 33)
2022-04-17 22:56:01,236 - ****************************************************************************************************
2022-04-17 22:56:01,242 - PriceDayRangeHourWise : BBM_15_2.0 : BBM_20_2.0 : 09:00 : 10:30 : price_range
2022-04-17 22:56:01,551 - PriceDayRangeHourWise : BBM_15_2.0 : BBM_20_2.0 : 09:00 : 10:30 : price_deviation_max_first_col
2022-04-17 22:56:03,238 - PriceDayRangeHourWise : BBM_15_2.0 : BBM_20_2.0 : 10:30 : 11:30 : price_range
2022-04-17 22:56:03,502 - PriceDayRangeHourWise : BBM_15_2.0 : BBM_20_2.0 : 10:30 : 11:30 : price_deviation_max_first_col
2022-04-17 22:56:04,852 - Shape of dataframe after PriceDayRangeHourWise is (1108035, 35)
2022-04-17 22:56:04,981 - ****************************************************************************************************
2022-04-17 22:56:07,901 - Shape of dataframe after PricePerVelocity is (1108035, 60)
2022-04-17 22:56:08,032 - ****************************************************************************************************
2022-04-17 22:56:10,703 - Shape of dataframe after PricePerVelocity is (1108035, 85)
2022-04-17 22:56:10,812 - ****************************************************************************************************
2022-04-17 22:56:10,814 - PriceDayRangeHourWise : high : low : 09:00 : 10:30 : price_range
2022-04-17 22:56:10,945 - PriceDayRangeHourWise : high : low : 09:00 : 10:30 : price_deviation_max_first_col
2022-04-17 22:56:12,098 - PriceDayRangeHourWise : high : low : 10:30 : 11:30 : price_range
2022-04-17 22:56:12,231 - PriceDayRangeHourWise : high : low : 10:30 : 11:30 : price_deviation_max_first_col
2022-04-17 22:56:14,149 - Shape of dataframe after PriceDayRangeHourWise is (1108035, 87)

Wall time: 1min 12s

In [9]:
base_df2['MACD_8_21_9_D_5_price_per_velocity'].value_counts()

 0.957925    1
-6.124548    1
 1.239477    1
 0.985036    1
 0.697896    1
            ..
-0.791481    1
-1.167240    1
-1.465812    1
-1.632866    1
-4.146211    1
Name: MACD_8_21_9_D_5_price_per_velocity, Length: 625192, dtype: int64

In [10]:
base_df2.between_time('12:29','13:10')

,open,high,low,close,SMA_50,SMA_200,BBL_20_2.0,BBM_20_2.0,BBU_20_2.0,BBB_20_2.0,...,RSI_20_D_5_price_per_velocity,RSI_100_D_5_price_per_velocity,MACD_8_21_9_D_5_price_per_velocity,MACDh_8_21_9_D_5_price_per_velocity,MACDs_8_21_9_D_5_price_per_velocity,MACD_15_30_9_D_5_price_per_velocity,MACDh_15_30_9_D_5_price_per_velocity,MACDs_15_30_9_D_5_price_per_velocity,PDR_high_low_price_deviation_max_first_col_0900_1030,PDR_high_low_price_deviation_max_first_col_1030_1130
2010-03-02 12:29:00,8895.00,8900.25,8894.70,8899.75,8891.668,8882.98325,8884.774383,8892.0925,8899.410617,0.164598,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-31.611111,-21.328689
2010-03-02 12:30:00,8899.80,8902.15,8899.30,8900.45,8891.698,8883.16075,8884.495902,8892.6050,8900.714098,0.182378,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-31.611111,-21.328689
2010-03-02 12:31:00,8900.15,8904.25,8900.15,8902.25,8891.784,8883.35425,8884.201744,8893.2225,8902.243256,0.202868,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-31.611111,-21.328689
2010-03-02 12:32:00,8900.00,8903.70,8899.90,8903.70,8891.908,8883.53350,8883.889128,8893.8875,8903.885872,0.224837,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-31.611111,-21.328689
2010-03-02 12:33:00,8904.85,8909.50,8903.35,8909.50,8892.239,8883.74025,8883.546029,8895.0425,8906.538971,0.258492,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-31.611111,-21.328689
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2022-01-13 13:06:00,38453.95,38461.35,38449.80,38451.70,38476.575,38511.57775,38439.488479,38456.8250,38474.161521,0.090161,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-153.778289,-55.617213
2022-01-13 13:07:00,38452.80,38457.40,38421.75,38429.65,38474.252,38510.51550,38437.629312,38454.1100,38470.590688,0.085716,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-153.778289,-55.617213
2022-01-13 13:08:00,38427.95,38429.15,38418.20,38427.00,38472.004,38509.38100,38432.462667,38452.4225,38472.382333,0.103816,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-153.778289,-55.617213
2022-01-13 13:09:00,38425.70,38440.35,38424.35,38434.45,38469.864,38508.24800,38430.188985,38451.6275,38473.066015,0.111509,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-153.778289,-55.617213
2022-01-13 13:10:00,38437.95,38450.55,38435.65,38441.65,38467.931,38507.18950,38429.152405,38450.8375,38472.522595,0.112794,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-153.778289,-55.617213

In [11]:
target_cols = ['label_-15_1min_close','label_-30_1min_close']

In [12]:
base_df3 = base_df2.dropna()

In [13]:
base_df3['label_-15_1min_close'].value_counts()

below100    321162
20to40       72764
10to20       70585
-10to-20     69460
40to60       28901
unknown      25005
60to80       13108
above100     10550
80to100       7163
-10to10        484
Name: label_-15_1min_close, dtype: int64

In [14]:
base_df3['label_-30_1min_close'].value_counts()

below100    295592
20to40       72673
10to20       55763
-10to-20     55549
unknown      50004
40to60       36758
above100     21968
60to80       19375
80to100      11145
-10to10        355
Name: label_-30_1min_close, dtype: int64

In [15]:
final_cols = [col for col in base_df3.columns.to_list() if col not in all_cols]
base_df3 = base_df3[final_cols]
base_df3_30 = base_df3[[col for col in base_df3.columns.tolist() if col != 'label_-15_1min_close']]
base_df3_15 = base_df3[[col for col in base_df3.columns.tolist() if col != 'label_-30_1min_close']]
base_df3_30.to_csv(r'C:\Users\8prab\Google Drive\Work\trading\database_df3_30.csv')
base_df3_15.to_csv(r'C:\Users\8prab\Google Drive\Work\trading\database_df3_15.csv')

In [24]:
from pycaret.classification import *

In [25]:
exp_mclf101 = setup(data = base_df3_15, target = 'label_-15_1min_close', session_id=123)

2022-04-17 19:22:39,572 - create_model_container: 0
2022-04-17 19:22:39,573 - master_model_container: 0
2022-04-17 19:22:39,574 - display_container: 1
2022-04-17 19:22:39,584 - Pipeline(memory=None,
         steps=[('dtypes',
                 DataTypes_Auto_infer(categorical_features=[],
                                      display_types=True, features_todrop=[],
                                      id_columns=[],
                                      ml_usecase='classification',
                                      numerical_features=[],
                                      target='label_-15_1min_close',
                                      time_features=[])),
                ('imputer',
                 Simple_Imputer(categorical_strategy='not_available',
                                fill_value_categorical=None,
                                fill_value_numerical=None...
                ('scaling', 'passthrough'), ('P_transform', 'passthrough'),
                ('binn', 'passthrough'), ('rem_outliers', 'passthrough'),
                ('cluster_all', 'passthrough'),
                ('dummy', Dummify(target='label_-15_1min_close')),
                ('fix_perfect', Remove_100(target='label_-15_1min_close')),
                ('clean_names', Clean_Colum_Names()),
                ('feature_select', 'passthrough'), ('fix_multi', 'passthrough'),
                ('dfs', 'passthrough'), ('pca', 'passthrough')],
         verbose=False)
2022-04-17 19:22:39,586 - setup() succesfully completed......................................

In [26]:
best = compare_models()

2022-04-17 19:24:30,548 - create_model_container: 0
2022-04-17 19:24:30,549 - master_model_container: 0
2022-04-17 19:24:30,551 - display_container: 2
2022-04-17 19:24:30,552 - []
2022-04-17 19:24:30,553 - compare_models() succesfully completed......................................